export PS1='\[\033[01;33m\]\u\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
export PS2='> '
export PS4='+ '
export LANG=en_US.UTF-8

echo Welcome to Dolphin terminal emulator'!'
echo Scroll up and down using Ctrl-Up, Ctrl-Down, Ctrl-PageUp and Ctrl-PageDown.
echo Output handling is based on JSLinux term.js library. Enjoy'!'